### ISSUE TITLE
0.8.4: When stopping: free(): invalid pointer

### ISSUE THREAD

**Issue by SjonHortensius** [gssapi/gssproxy#36]
I'm not very familiar with what gssproxy is supposed to do, but I'm using `gssproxy 0.8.4` on archlinux on a fairly simple desktop that is also an nfs client. I noticed gssproxy has been crashing for months, which sometimes makes my machine hang on shutdown.

I have some interesting logs, on start:
```
gssproxy[XXX]: Error when reading config directory: File /etc/gssproxy/gssproxy.conf did not match provided patterns. Skipping.
```

this file contains the default as provided by my distro, it's content is:
```
[gssproxy]
```

When stopping gssproxy:
```
gssproxy[XXX: free(): invalid pointer

Stack trace of thread XXX:
#0  0x00007f1f5eb8cd22 raise (libc.so.6 + 0x3cd22)
#1  0x00007f1f5eb76862 abort (libc.so.6 + 0x26862)
#2  0x00007f1f5ebced28 __libc_message (libc.so.6 + 0x7ed28)
#3  0x00007f1f5ebd692a malloc_printerr (libc.so.6 + 0x8692a)
#4  0x00007f1f5ebd7cfc _int_free (libc.so.6 + 0x87cfc)
#5  0x00007f1f5ebdb9e8 __libc_free (libc.so.6 + 0x8b9e8)
#6  0x00007f1f5edd9fbc verto_cleanup (libverto.so.0 + 0x2fbc)
#7  0x000056306f8bc783 n/a (gssproxy + 0x5783)
#8  0x00007f1f5eb77b25 __libc_start_main (libc.so.6 + 0x27b25)
#9  0x000056306f8bc92e n/a (gssproxy + 0x592e)
```

I see a reference to `verto_cleanup`; this is provided by `libverto.so.0.0` which is provided by `krb5 1.19.2`

**Comment by simo5** [comment]
Are you suing krb5 authentication for your NFS mounts? That's what gssproxy is used for normally.
You may see nfs related configuration files under /etc/gssproxy/99-nfs-client.conf
It is fine that the main gssproxy conf file is empty if thre are nor general directives to apply to change the default general configuration.

On libverto it is very odd if it is provided by the krb5 package. Krb5 does have an old vendored version of libeverto in case one is not installed on the system, but the correct way to build it would be to provide the verto package on the distro and then build krb5 against it.

For example in Fedora 34 we have libverto-0.3.2-1.fc34.x86_64.rpm which provides /usr/lib64/libverto.so.1.0.0

At any rate verto_cleanup() is a function w/o parameters, if it crashes it means there is a bug in the verto version used in your distribution, or, potentially worse, there are two versions of libverto loaded in your address space (one linked by gssproxy, and one built statically into krb5) and symbols are clashing.

Nothing that can be solved on the gssproxy side at any rate.
