### ISSUE TITLE
[0.9.0] doesn't allow disabled systemd

### ISSUE THREAD

**Issue by udeved** [gssapi/gssproxy#54]
With version 0.9.9, despite `--with-initscript=none`, the build errors out with

```
configure: error: conditional "HAVE_SYSTEMD_DAEMON" was never defined.
Usually this means the macro was only invoked conditionally.
```

I think this commit is responsible, but haven't tracked it down further.
Might be the m4 systemd macro.

https://github.com/gssapi/gssproxy/commit/145c7cecb9d7aecb707c02995b0289b40a6df4d7

**Comment by udeved** [comment]
It won't get to make phase, it fails at configure.
We have neither systemd nor libsystemd present.
I haven't tracked it down further, but it looks to me as if the systemd.m4 has no case for setting HAVE_SYSTEMD_DAEMON to 0 hence the error msg of undefined.

**Comment by udeved** [comment]
[gssproxy-0.9.0-1-x86_64-build.log](https://pastebin.com/nrYRp3F5)

**Comment by simo5** [comment]
@udeved Are you able to apply the fix in #55 and let me know if it works for you?

you will need to run autoreconf -fi before running configure.

**Comment by udeved** [comment]
Yes, sure. 
Will report back.

**Comment by udeved** [comment]
Yes, that PR fixes the configure.  :+1: 
[log](https://pastebin.com/zrZtrjST)
