### ISSUE TITLE
Variable substitution for hostname / FDQN

### ISSUE THREAD

**Issue by tiran** [gssapi/gssproxy#81]
I like to request a new config variable as substitution for host's current FDQN. This would allow me to have a reusable gssproxy config file with `krb5_principal` set to a service principal name. The service principal contains the current FQDN, e.g. `myservice/host.ipa.example`. If gssproxy would support an additional variable, I could ship the config file in RPM packages.

```
[service/myservice]
  mechs = krb5
  cred_store = keytab:/var/lib/ipa/gssproxy/myservice.keytab
  allow_client_ccache_sync = true
  cred_usage = initiate
  euid = myservice
  # krb5_principal = myservice/host.ipa.example
   krb5_principal = myservice/%h
```

The `krb5_principal` option is required to initiate credentials without explicit principal name in the user application. For example `ipa` command line tool and its API need `krb5_principal` to automatically authenticate.

```
# sudo -u myservice /bin/bash
bash-5.1$ GSS_USE_PROXY=1 ipa ping
--------------------------------------------
IPA server version 4.10.1. API version 2.251
--------------------------------------------
```

Without an explicit `krb5_principal`, the command fails, because `GSSX_ARG_ACQUIRE_CRED` runs with `input_cred_handle: <Null>`.

FreeIPA ticket https://pagure.io/freeipa/issue/9442 has some context.

**Comment by tiran** [comment]
> This is odd, isn't the caller passing in a principal when acquiring creds?

In my test case, the caller does neither specify a principal name nor does the caller have a ccache or access to the keytab.

I'm trying to achieve the same behavior as `KRB5_CLIENT_KTNAME=/path/to/mservice.keytab ipa ping`. With `KRB5_CLIENT_KTNAME`, the caller does not need to know the principal name. GSSAPI get the principal from the first keytab entry and automatically acquires credentials for it.

https://pagure.io/freeipa/issue/9442 has more information.

**Comment by tiran** [comment]
Because I copied the wrong example config and wasn't aware that `cred_store` has a `client_keytab` option...

It works like a charm with `client_keytab:`. The `krb5_principal` option is not necessary with `client_keytab`:.

**Comment by simo5** [comment]
Great, in that case I will close this issue.
